import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      {/* <div>
          <iframe src="https://chatbot-builder-nextjs.vercel.app/"  className="w-[300px] h-[600px] "></iframe>
      </div> */}
      </body>
    </html>
  )
}
